#! /usr/bin/python
# -*- coding: utf-8 -*-
import sys, os, os.path
fn=os.path.expanduser('~/.monajat-applet-skip-auto')
if '--auto' in sys.argv and os.path.exists(fn): exit(0)
from monajat.applet import applet_main
applet_main()
